// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMWoM5t-kDy7trFzPSbUWDFXsNZ8ESsVc',
    appId: '1:589312749561:web:9706b8167746a637261728',
    messagingSenderId: '589312749561',
    projectId: 'chatapp-aa76d',
    authDomain: 'chatapp-aa76d.firebaseapp.com',
    storageBucket: 'chatapp-aa76d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMCcG0VC6QGjHuwxFcxhItsflV1yJUMZo',
    appId: '1:589312749561:android:0dac785b354115e1261728',
    messagingSenderId: '589312749561',
    projectId: 'chatapp-aa76d',
    storageBucket: 'chatapp-aa76d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuc_umt8g76yesI7ghpHurvrfSQV03lkk',
    appId: '1:589312749561:ios:679ec26a4a930227261728',
    messagingSenderId: '589312749561',
    projectId: 'chatapp-aa76d',
    storageBucket: 'chatapp-aa76d.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuc_umt8g76yesI7ghpHurvrfSQV03lkk',
    appId: '1:589312749561:ios:679ec26a4a930227261728',
    messagingSenderId: '589312749561',
    projectId: 'chatapp-aa76d',
    storageBucket: 'chatapp-aa76d.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMWoM5t-kDy7trFzPSbUWDFXsNZ8ESsVc',
    appId: '1:589312749561:web:25dd247858bc6af4261728',
    messagingSenderId: '589312749561',
    projectId: 'chatapp-aa76d',
    authDomain: 'chatapp-aa76d.firebaseapp.com',
    storageBucket: 'chatapp-aa76d.firebasestorage.app',
  );
}
